- imageUrl: "https://www.codefactor.io/repository/github/$slug/badge"
  url: "https://www.codefactor.io/repository/github/$slug"

- imageUrl: "https://codecov.io/gh/$slug/branch/main/graph/badge.svg?token=ZQ0WR3ZSWG"
  url: "https://codecov.io/gh/$slug"

- label: "Error Branch"
  message: "$payload.pull_request.base.ref"
  color: "#ff0000"
  when: "$payload.pull_request.base.ref !== 'main'"
